import { chromium } from 'playwright';
import { writeFileSync } from 'node:fs';
import { pathToFileURL } from 'url';
const file = process.argv[2] || 'assets/hero.svg';
const out = process.argv[3] || 'shot.png';
const wait = Number(process.argv[4] || 3200);
const scheme = process.argv[5] || 'dark';
const html = `<!doctype html><body style="margin:0;padding:20px;background:${scheme === 'dark' ? '#0d1117' : '#ffffff'}"><img src="${file}" style="width:960px;display:block"></body>`;
writeFileSync('_shot.html', html);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1000, height: 520 }, colorScheme: scheme, deviceScaleFactor: 1 });
await p.goto(pathToFileURL(process.cwd() + '/_shot.html').href);
await p.waitForTimeout(wait);
await p.screenshot({ path: out });
await b.close();
